version: '3.1'
services:
  dbserver:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    hostname: dbserver
    environment:
      MYSQL_DATABASE: lftvweb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: lftv
      MYSQL_PASSWORD: secret
  wordpress:
    depends_on:
      - dbserver
    image: wordpress:5.2.2-php7.3-fpm-alpine
    ports:
      - 8888:80
      - 443:443
    restart: always
    volumes:
      - ./wp-content/:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: dbserver
      WORDPRESS_DB_USER: lftv
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: lftvweb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8889:8080
volumes:
  db_data: