# Use root/example as user/password credentials
version: '3.1'
services:
  mysql:
    image: "mysql:8.0.19"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
      - '33060:33060'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: demo
    volumes:
      - ./mysql/_log:/var/log/mysql
      - ./mysql/_data:/var/lib/mysql
      - ./mysql/me-config:/etc/mysql
      - ./mysql/init_data/data.sql:/docker-entrypoint-initdb.d/data.sql


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080